package com.style103.mybatis.mapper;

import com.style103.mybatis.pojo.Dept;
import com.style103.mybatis.pojo.DeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    long countByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    int deleteByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    int deleteByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    List<Dept> selectByExample(DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    Dept selectByPrimaryKey(Integer depId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    int updateByExampleSelective(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    int updateByExample(@Param("record") Dept record, @Param("example") DeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dep
     *
     * @mbg.generated Sat Dec 21 16:55:15 CST 2024
     */
    int updateByPrimaryKey(Dept record);
}